Switch to use swift-argument-parser and add a --verbose switch
ctreffs/SwiftSimctl pull request #11
Opened 2020-12-01 14:09 UTC by tamc

This PR switches to using the swift-argument-parser package and then adds a --verbose flag to start-server subcommand

The --verbose flag causes the server to print the command that is being run and the output of that command

2020-12-02 08:29 UTC, ctreffs commented
Thanks for contributing this, I originally started with ArgumentParser, but back then it was not compatible enough. 
Let's give it another try now 👍

2020-12-02 08:46 UTC, ctreffs requested changes
Very nice PR, thank you for your contribution!
I just hat two nitpicks, other then that I would merge it.

One more thing - to make the PR complete, it would be nice, if you generate the new version of the binary `SimctlCLI`, that can be achieved by calling `make buildSimctlCLI`.
That updates the executable in `bin/` which is necessary to run the tests.
Thank you :-)

2020-12-02 08:46 UTC, ctreffs commented on Sources/SimctlCLI/ListDevices.swift
> +//  SimctlCLI.swift
I know it's a nitpick, but would be nice to rename the header comment to be equal to the file name.

2020-12-02 08:46 UTC, ctreffs commented on Sources/SimctlCLI/StartServer.swift
> +//  SimctlCLI.swift
Same here :-)

2021-04-14 17:24 UTC, scott-mcalister commented
Hey @tamc, are you planning on wrapping up this request?

2021-04-14 17:34 UTC, rsmcalister commented
Hey @tamc, are you planning on wrapping up this request?

2021-04-19 16:39 UTC, ctreffs commented
That would be great. Please do 👍🏻

2021-04-29 05:07 UTC, ctreffs commented
Closed by https://github.com/ctreffs/SwiftSimctl/pull/12

2021-04-29 05:07 UTC, closed without merging